# run: conda env create --file environment.yml
# include new packages: conda env update --file environment.yml
name: example_env
channels:
  - conda-forge
  - tudat-team
  - conda
dependencies:
- anaconda
- nb_conda
- conda:
  - pytest=6.1.2
  - nbconvert
  - matplotlib
  - ipykernel
  - tudatpy
  - nb_conda
- pip
- pip:
  # works for regular pip packages
  - pdflatex
  - testbook
  - pyment
  - pdoc3
  - black